### ISSUE TITLE
determine which bundles are already on chain and update docs

### ISSUE THREAD

**Issue by 0xpatrickdev** [0xpatrickdev/psm-proposals#2]
The current proposal references three bundles (psm.js, startPSM.js, mintHolder.js). [This discussion](https://github.com/Agoric/agoric-sdk/discussions/8450) mentions that 2 should already be present on chain.

- `b1-820164f689d730163488efe6911b89f4f4dfb9b11b33b711c24340416c7ea90ec6a311ceb8c26cc2d1c6624e8d5b714c73eab1a08d99bb81c22d815acefd94fd.json`
- `b1-d6bf1435f5ef0fc5f8386bc6f6d4563f9f2b8c1117d7d778e39d34601436d78cac7e5000f73857ed5b3dcc76742ff0d392d8a3e3164d7775a9c85ed0c30fdeda.json`
- `b1-eb7db38002a9f53cb6df39c5b23c816d8b6381c1388c9fec772e0cdbb055f55641da9219a4891ecee5697c9cc3c6a988d0ffa75d191e806f4867990b4ce3df83.json`

**Comment by 0xpatrickdev** [comment]
If someone could run this from an `agoric-3` node, and share the output, that should answer this question.

```bash
sqlite3 $AGORIC_HOME/data/agoric/swingstore.sqlite "SELECT bundleID FROM bundles WHERE bundleID LIKE 'b1-820164%' OR bundleID LIKE 'b1-d6bf14%' OR bundleID LIKE 'b1-eb7db3%';"
```

**Comment by dckc** [comment]
[mainnet1B-bundle-ids.md](https://gist.github.com/dckc/4088fb3cf7b568ce81ddabab2817f336#file-mainnet1b-bundle-ids-md) is the full list as of Aug 23

I don't see `b1-820164` nor `b1-d6bf14` in there.

**Comment by 0xpatrickdev** [comment]
Ok thanks. It seems I might need to regenerate the scripts in a way where the existing `mintHolder` and `psm` from the chain are referenced. 

Updating op with your handy https://bexp.netlify.app/:

| bundleId | contents | bytes | price |
|----------|----------|-------|-------|
| `b1-820164...fd94fd` | `{"compartment":"@agoric/vats-v0.15.1","module":"./src/mintHolder.js"}` | 935505 | 1871.01 |
| `b1-d6bf14...0fdeda` | `{"compartment":"@agoric/inter-protocol-v0.16.1","module":"./src/psm/psm.js"}` | 1402469 | 2804.938 |
| `b1-eb7db3...e3df83` | `{"compartment":"@agoric/inter-protocol-v0.16.1","module":"./src/proposals/startPSM.js"}` | 1319597 | 2639.194 |


<blockquote><div><strong><a href="https://bexp.netlify.app/">Bundle Explorer - Agoric</a></strong></div></blockquote>

**Comment by dckc** [comment]
Yes... Much like in https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/pull/25

**Comment by dckc** [comment]
A nit: bundleIds don't include .json

**Comment by 0xpatrickdev** [comment]
I have also realized i can glean bundles from `/deployment/upgrade-test` :homer-doh: 


```
## Terminal 1 
cd ~/agoric-sdk/packages/deployment/upgrade-test
make run_bash
agd start --log_level warn
```

```
## Terminal 2
docker ps # list containers
docker exec -ti CONAINTER_ID bash
apt install -y sqlite3
sqlite3 ~/.agoric/data/agoric/swingstore.sqlite "SELECT bundleID FROM bundles ORDER BY bundleID;"

**Comment by 0xpatrickdev** [comment]
see https://github.com/0xpatrickdev/psm-proposals/pull/3/commits/1af695b3e6ae4cddea85271de03f490b27f8b129 and  #3
